In [ ]:
import pandas as pd

df = pd.read_parquet('data/TSLA_1min.parquet')

df[df.timestamp.dt.date == '2025-07-21']

Empty DataFrame
Columns: [timestamp, symbol, open, close, high, low, mean, std, trade_count, volume, dollar_volume, cond_is_regular, odd_lot_count, buy_volume, sell_volume, order_flow_imbalance, dollar_order_flow_imbalance, kyle_lambda, avg_price_acceleration, price_acceleration_std, consecutive_trades_ratio, volume_weighted_momentum, avg_trade_size, trade_size_std, max_trade_size, buy_trade_count, sell_trade_count, intertrade_ms_mean, intertrade_ms_std, intertrade_ms_min, intertrade_ms_max, cnt_large, cnt_mid, cnt_small, cnt_tiny, vwap, order_flow_ratio, dollar_order_flow_ratio, buy_sell_ratio, trade_direction_ratio, price_impact_per_dollar, trade_return, volatility_proxy, price_range, mid_bar_pos, turnover_rate, trade_intensity, roll_spread_proxy, price_reversal]
Index: []

[0 rows x 49 columns]

In [128]:
df = pd.read_parquet('data/TSLA_1min.parquet')

df

,timestamp,symbol,open,close,high,low,mean,std,trade_count,volume,...,trade_direction_ratio,price_impact_per_dollar,trade_return,volatility_proxy,price_range,mid_bar_pos,turnover_rate,trade_intensity,roll_spread_proxy,price_reversal
0,2024-01-02 14:30:00,TSLA,250.240,249.95,250.86,249.610,250.288534,0.343012,208.0,13544.0,...,-0.038462,0.000129,-0.000120,0.001370,0.004995,0.272000,208.0,366.675961,7.686148e-08,-0.0000
1,2024-01-02 14:31:00,TSLA,249.990,249.11,249.99,248.920,249.529111,0.333728,45.0,3799.0,...,-0.133333,0.000215,-0.003361,0.001337,0.004280,0.177570,45.0,34.431883,4.033129e-07,0.2552
2,2024-01-02 14:32:00,TSLA,249.120,249.08,249.43,249.020,249.231667,0.117734,45.0,2770.0,...,0.200000,0.000198,-0.000120,0.000472,0.001646,0.146341,45.0,32.930184,4.047215e-07,0.0352
3,2024-01-02 14:33:00,TSLA,249.060,246.44,249.07,246.350,247.646092,0.854728,87.0,4412.0,...,-0.310345,0.000171,-0.010599,0.003451,0.010921,0.033088,87.0,126.251805,1.276425e-06,0.1048
4,2024-01-02 14:34:00,TSLA,246.425,245.06,246.47,245.050,245.794245,0.385518,106.0,4675.0,...,-0.207547,0.000109,-0.005600,0.001568,0.005762,0.007042,106.0,187.297311,5.935167e-05,3.5763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152547,2025-07-25 19:56:00,TSLA,315.950,316.17,316.36,315.920,316.153861,0.118269,101.0,6711.0,...,0.099010,0.000083,0.000633,0.000374,0.001393,0.568182,101.0,171.738335,1.279498e-06,-0.0330
152548,2025-07-25 19:57:00,TSLA,316.220,316.01,316.38,315.985,316.218443,0.079685,122.0,7824.0,...,-0.016393,0.000056,-0.000506,0.000252,0.001249,0.063291,122.0,245.179973,3.203196e-07,-0.0462
152549,2025-07-25 19:58:00,TSLA,315.970,315.96,316.10,315.890,315.967403,0.043554,129.0,8455.0,...,0.023256,0.000040,-0.000158,0.000138,0.000665,0.333333,129.0,277.770686,8.006976e-08,0.0021
152550,2025-07-25 19:59:00,TSLA,315.970,316.07,316.09,315.880,315.973679,0.050240,246.0,21253.0,...,0.040650,0.000026,0.000348,0.000159,0.000665,0.904762,246.0,1006.383609,5.508454e-08,-0.0010
152551,2025-07-25 20:00:00,TSLA,315.920,315.91,315.92,315.910,315.915000,0.007071,2.0,10.0,...,-1.000000,0.000253,-0.000506,0.000022,0.000032,0.000000,2.0,0.079533,1.762371e-07,-0.0010

In [127]:
import datetime
import pandas as pd
df = pd.DataFrame([{"a": 1, "b": 2, "c": 3}, {}])
df

     a    b    c
0  1.0  2.0  3.0
1  NaN  NaN  NaN

In [71]:
from datetime import datetime
import pytz

def nyc_now() -> datetime:
    return datetime.now(pytz.timezone("UTC")).replace(tzinfo=None)
nyc_now()

datetime.datetime(2025, 7, 24, 18, 45, 46, 914698)

In [124]:
from pandas_market_calendars import get_calendar, date_range
import pandas as pd

nyse = get_calendar("NYSE")
start_time = "2025-07-23 20:01:00"
end_time = "2025-07-24 19:00:00"
start_date = pd.to_datetime(start_time).tz_localize(None)
end_date = pd.to_datetime(end_time).tz_localize(None)

sched = nyse.schedule(start_date=start_date, end_date=end_date, tz="UTC")
canon_idx = date_range(sched, frequency="1min", closed="both")
canon_idx = canon_idx.tz_localize(None)

In [125]:
canon_idx = [idx for idx in canon_idx if idx >= pd.to_datetime(start_time)]
canon_idx = [idx for idx in canon_idx if idx <= pd.to_datetime(end_time)]
canon_idx

[Timestamp('2025-07-24 13:30:00'),
 Timestamp('2025-07-24 13:31:00'),
 Timestamp('2025-07-24 13:32:00'),
 Timestamp('2025-07-24 13:33:00'),
 Timestamp('2025-07-24 13:34:00'),
 Timestamp('2025-07-24 13:35:00'),
 Timestamp('2025-07-24 13:36:00'),
 Timestamp('2025-07-24 13:37:00'),
 Timestamp('2025-07-24 13:38:00'),
 Timestamp('2025-07-24 13:39:00'),
 Timestamp('2025-07-24 13:40:00'),
 Timestamp('2025-07-24 13:41:00'),
 Timestamp('2025-07-24 13:42:00'),
 Timestamp('2025-07-24 13:43:00'),
 Timestamp('2025-07-24 13:44:00'),
 Timestamp('2025-07-24 13:45:00'),
 Timestamp('2025-07-24 13:46:00'),
 Timestamp('2025-07-24 13:47:00'),
 Timestamp('2025-07-24 13:48:00'),
 Timestamp('2025-07-24 13:49:00'),
 Timestamp('2025-07-24 13:50:00'),
 Timestamp('2025-07-24 13:51:00'),
 Timestamp('2025-07-24 13:52:00'),
 Timestamp('2025-07-24 13:53:00'),
 Timestamp('2025-07-24 13:54:00'),
 Timestamp('2025-07-24 13:55:00'),
 Timestamp('2025-07-24 13:56:00'),
 Timestamp('2025-07-24 13:57:00'),
 Timestamp('2025-07-24 13:58:00'),
 Timestamp('2025-07-24 13:59:00'),
 Timestamp('2025-07-24 14:00:00'),
 Timestamp('2025-07-24 14:01:00'),
 Timestamp('2025-07-24 14:02:00'),
 Timestamp('2025-07-24 14:03:00'),
 Timestamp('2025-07-24 14:04:00'),
 Timestamp('2025-07-24 14:05:00'),
 Timestamp('2025-07-24 14:06:00'),
 Timestamp('2025-07-24 14:07:00'),
 Timestamp('2025-07-24 14:08:00'),
 Timestamp('2025-07-24 14:09:00'),
 Timestamp('2025-07-24 14:10:00'),
 Timestamp('2025-07-24 14:11:00'),
 Timestamp('2025-07-24 14:12:00'),
 Timestamp('2025-07-24 14:13:00'),
 Timestamp('2025-07-24 14:14:00'),
 Timestamp('2025-07-24 14:15:00'),
 Timestamp('2025-07-24 14:16:00'),
 Timestamp('2025-07-24 14:17:00'),
 Timestamp('2025-07-24 14:18:00'),
 Timestamp('2025-07-24 14:19:00'),
 Timestamp('2025-07-24 14:20:00'),
 Timestamp('2025-07-24 14:21:00'),
 Timestamp('2025-07-24 14:22:00'),
 Timestamp('2025-07-24 14:23:00'),
 Timestamp('2025-07-24 14:24:00'),
 Timestamp('2025-07-24 14:25:00'),
 Timestamp('2025-07-24 14:26:00'),
 Timestamp('2025-07-24 14:27:00'),
 Timestamp('2025-07-24 14:28:00'),
 Timestamp('2025-07-24 14:29:00'),
 Timestamp('2025-07-24 14:30:00'),
 Timestamp('2025-07-24 14:31:00'),
 Timestamp('2025-07-24 14:32:00'),
 Timestamp('2025-07-24 14:33:00'),
 Timestamp('2025-07-24 14:34:00'),
 Timestamp('2025-07-24 14:35:00'),
 Timestamp('2025-07-24 14:36:00'),
 Timestamp('2025-07-24 14:37:00'),
 Timestamp('2025-07-24 14:38:00'),
 Timestamp('2025-07-24 14:39:00'),
 Timestamp('2025-07-24 14:40:00'),
 Timestamp('2025-07-24 14:41:00'),
 Timestamp('2025-07-24 14:42:00'),
 Timestamp('2025-07-24 14:43:00'),
 Timestamp('2025-07-24 14:44:00'),
 Timestamp('2025-07-24 14:45:00'),
 Timestamp('2025-07-24 14:46:00'),
 Timestamp('2025-07-24 14:47:00'),
 Timestamp('2025-07-24 14:48:00'),
 Timestamp('2025-07-24 14:49:00'),
 Timestamp('2025-07-24 14:50:00'),
 Timestamp('2025-07-24 14:51:00'),
 Timestamp('2025-07-24 14:52:00'),
 Timestamp('2025-07-24 14:53:00'),
 Timestamp('2025-07-24 14:54:00'),
 Timestamp('2025-07-24 14:55:00'),
 Timestamp('2025-07-24 14:56:00'),
 Timestamp('2025-07-24 14:57:00'),
 Timestamp('2025-07-24 14:58:00'),
 Timestamp('2025-07-24 14:59:00'),
 Timestamp('2025-07-24 15:00:00'),
 Timestamp('2025-07-24 15:01:00'),
 Timestamp('2025-07-24 15:02:00'),
 Timestamp('2025-07-24 15:03:00'),
 Timestamp('2025-07-24 15:04:00'),
 Timestamp('2025-07-24 15:05:00'),
 Timestamp('2025-07-24 15:06:00'),
 Timestamp('2025-07-24 15:07:00'),
 Timestamp('2025-07-24 15:08:00'),
 Timestamp('2025-07-24 15:09:00'),
 Timestamp('2025-07-24 15:10:00'),
 Timestamp('2025-07-24 15:11:00'),
 Timestamp('2025-07-24 15:12:00'),
 Timestamp('2025-07-24 15:13:00'),
 Timestamp('2025-07-24 15:14:00'),
 Timestamp('2025-07-24 15:15:00'),
 Timestamp('2025-07-24 15:16:00'),
 Timestamp('2025-07-24 15:17:00'),
 Timestamp('2025-07-24 15:18:00'),
 Timestamp('2025-07-24 15:19:00'),
 Timestamp('2025-07-24 15:20:00'),
 Timestamp('2025-07-24 15:21:00'),
 Timestamp('2025-07-24 15:22:00'),
 Timestamp('2025-07-24 15:23:00'),
 Timestamp('2025-07-24 15:24:00'),
 Timestamp('2025-07-24 15:25:00'),
 Timestamp('2025-07-24 15:26:00'),
 Timestamp('2025-07-24 15:27:00'),
 Timestamp('2025-07-24 15:28:00'),
 Timestamp('2025-07-24 15:29:00'),
 Timestamp('2025-07-24 15:30:00'),
 Timestamp('2025-07-24 15:31:00'),
 Timestamp('2025-07-24 15:32:00'),
 Timestamp('2025-07-24 15:33:00'),
 Timestamp('2025-07-24 15:34:00'),
 Timestamp('2025-07-24 15:35:00'),
 Timestamp('2025-07-24 15:36:00'),
 Timestamp('2025-07-24 15:37:00'),
 Timestamp('2025-07-24 15:38:00'),
 Timestamp('2025-07-24 15:39:00'),
 Timestamp('2025-07-24 15:40:00'),
 Timestamp('2025-07-24 15:41:00'),
 Timestamp('2025-07-24 15:42:00'),
 Timestamp('2025-07-24 15:43:00'),
 Timestamp('2025-07-24 15:44:00'),
 Timestamp('2025-07-24 15:45:00'),
 Timestamp('2025-07-24 15:46:00'),
 Timestamp('2025-07-24 15:47:00'),
 Timestamp('2025-07-24 15:48:00'),
 Timestamp('2025-07-24 15:49:00'),
 Timestamp('2025-07-24 15:50:00'),
 Timestamp('2025-07-24 15:51:00'),
 Timestamp('2025-07-24 15:52:00'),
 Timestamp('2025-07-24 15:53:00'),
 Timestamp('2025-07-24 15:54:00'),
 Timestamp('2025-07-24 15:55:00'),
 Timestamp('2025-07-24 15:56:00'),
 Timestamp('2025-07-24 15:57:00'),
 Timestamp('2025-07-24 15:58:00'),
 Timestamp('2025-07-24 15:59:00'),
 Timestamp('2025-07-24 16:00:00'),
 Timestamp('2025-07-24 16:01:00'),
 Timestamp('2025-07-24 16:02:00'),
 Timestamp('2025-07-24 16:03:00'),
 Timestamp('2025-07-24 16:04:00'),
 Timestamp('2025-07-24 16:05:00'),
 Timestamp('2025-07-24 16:06:00'),
 Timestamp('2025-07-24 16:07:00'),
 Timestamp('2025-07-24 16:08:00'),
 Timestamp('2025-07-24 16:09:00'),
 Timestamp('2025-07-24 16:10:00'),
 Timestamp('2025-07-24 16:11:00'),
 Timestamp('2025-07-24 16:12:00'),
 Timestamp('2025-07-24 16:13:00'),
 Timestamp('2025-07-24 16:14:00'),
 Timestamp('2025-07-24 16:15:00'),
 Timestamp('2025-07-24 16:16:00'),
 Timestamp('2025-07-24 16:17:00'),
 Timestamp('2025-07-24 16:18:00'),
 Timestamp('2025-07-24 16:19:00'),
 Timestamp('2025-07-24 16:20:00'),
 Timestamp('2025-07-24 16:21:00'),
 Timestamp('2025-07-24 16:22:00'),
 Timestamp('2025-07-24 16:23:00'),
 Timestamp('2025-07-24 16:24:00'),
 Timestamp('2025-07-24 16:25:00'),
 Timestamp('2025-07-24 16:26:00'),
 Timestamp('2025-07-24 16:27:00'),
 Timestamp('2025-07-24 16:28:00'),
 Timestamp('2025-07-24 16:29:00'),
 Timestamp('2025-07-24 16:30:00'),
 Timestamp('2025-07-24 16:31:00'),
 Timestamp('2025-07-24 16:32:00'),
 Timestamp('2025-07-24 16:33:00'),
 Timestamp('2025-07-24 16:34:00'),
 Timestamp('2025-07-24 16:35:00'),
 Timestamp('2025-07-24 16:36:00'),
 Timestamp('2025-07-24 16:37:00'),
 Timestamp('2025-07-24 16:38:00'),
 Timestamp('2025-07-24 16:39:00'),
 Timestamp('2025-07-24 16:40:00'),
 Timestamp('2025-07-24 16:41:00'),
 Timestamp('2025-07-24 16:42:00'),
 Timestamp('2025-07-24 16:43:00'),
 Timestamp('2025-07-24 16:44:00'),
 Timestamp('2025-07-24 16:45:00'),
 Timestamp('2025-07-24 16:46:00'),
 Timestamp('2025-07-24 16:47:00'),
 Timestamp('2025-07-24 16:48:00'),
 Timestamp('2025-07-24 16:49:00'),
 Timestamp('2025-07-24 16:50:00'),
 Timestamp('2025-07-24 16:51:00'),
 Timestamp('2025-07-24 16:52:00'),
 Timestamp('2025-07-24 16:53:00'),
 Timestamp('2025-07-24 16:54:00'),
 Timestamp('2025-07-24 16:55:00'),
 Timestamp('2025-07-24 16:56:00'),
 Timestamp('2025-07-24 16:57:00'),
 Timestamp('2025-07-24 16:58:00'),
 Timestamp('2025-07-24 16:59:00'),
 Timestamp('2025-07-24 17:00:00'),
 Timestamp('2025-07-24 17:01:00'),
 Timestamp('2025-07-24 17:02:00'),
 Timestamp('2025-07-24 17:03:00'),
 Timestamp('2025-07-24 17:04:00'),
 Timestamp('2025-07-24 17:05:00'),
 Timestamp('2025-07-24 17:06:00'),
 Timestamp('2025-07-24 17:07:00'),
 Timestamp('2025-07-24 17:08:00'),
 Timestamp('2025-07-24 17:09:00'),
 Timestamp('2025-07-24 17:10:00'),
 Timestamp('2025-07-24 17:11:00'),
 Timestamp('2025-07-24 17:12:00'),
 Timestamp('2025-07-24 17:13:00'),
 Timestamp('2025-07-24 17:14:00'),
 Timestamp('2025-07-24 17:15:00'),
 Timestamp('2025-07-24 17:16:00'),
 Timestamp('2025-07-24 17:17:00'),
 Timestamp('2025-07-24 17:18:00'),
 Timestamp('2025-07-24 17:19:00'),
 Timestamp('2025-07-24 17:20:00'),
 Timestamp('2025-07-24 17:21:00'),
 Timestamp('2025-07-24 17:22:00'),
 Timestamp('2025-07-24 17:23:00'),
 Timestamp('2025-07-24 17:24:00'),
 Timestamp('2025-07-24 17:25:00'),
 Timestamp('2025-07-24 17:26:00'),
 Timestamp('2025-07-24 17:27:00'),
 Timestamp('2025-07-24 17:28:00'),
 Timestamp('2025-07-24 17:29:00'),
 Timestamp('2025-07-24 17:30:00'),
 Timestamp('2025-07-24 17:31:00'),
 Timestamp('2025-07-24 17:32:00'),
 Timestamp('2025-07-24 17:33:00'),
 Timestamp('2025-07-24 17:34:00'),
 Timestamp('2025-07-24 17:35:00'),
 Timestamp('2025-07-24 17:36:00'),
 Timestamp('2025-07-24 17:37:00'),
 Timestamp('2025-07-24 17:38:00'),
 Timestamp('2025-07-24 17:39:00'),
 Timestamp('2025-07-24 17:40:00'),
 Timestamp('2025-07-24 17:41:00'),
 Timestamp('2025-07-24 17:42:00'),
 Timestamp('2025-07-24 17:43:00'),
 Timestamp('2025-07-24 17:44:00'),
 Timestamp('2025-07-24 17:45:00'),
 Timestamp('2025-07-24 17:46:00'),
 Timestamp('2025-07-24 17:47:00'),
 Timestamp('2025-07-24 17:48:00'),
 Timestamp('2025-07-24 17:49:00'),
 Timestamp('2025-07-24 17:50:00'),
 Timestamp('2025-07-24 17:51:00'),
 Timestamp('2025-07-24 17:52:00'),
 Timestamp('2025-07-24 17:53:00'),
 Timestamp('2025-07-24 17:54:00'),
 Timestamp('2025-07-24 17:55:00'),
 Timestamp('2025-07-24 17:56:00'),
 Timestamp('2025-07-24 17:57:00'),
 Timestamp('2025-07-24 17:58:00'),
 Timestamp('2025-07-24 17:59:00'),
 Timestamp('2025-07-24 18:00:00'),
 Timestamp('2025-07-24 18:01:00'),
 Timestamp('2025-07-24 18:02:00'),
 Timestamp('2025-07-24 18:03:00'),
 Timestamp('2025-07-24 18:04:00'),
 Timestamp('2025-07-24 18:05:00'),
 Timestamp('2025-07-24 18:06:00'),
 Timestamp('2025-07-24 18:07:00'),
 Timestamp('2025-07-24 18:08:00'),
 Timestamp('2025-07-24 18:09:00'),
 Timestamp('2025-07-24 18:10:00'),
 Timestamp('2025-07-24 18:11:00'),
 Timestamp('2025-07-24 18:12:00'),
 Timestamp('2025-07-24 18:13:00'),
 Timestamp('2025-07-24 18:14:00'),
 Timestamp('2025-07-24 18:15:00'),
 Timestamp('2025-07-24 18:16:00'),
 Timestamp('2025-07-24 18:17:00'),
 Timestamp('2025-07-24 18:18:00'),
 Timestamp('2025-07-24 18:19:00'),
 Timestamp('2025-07-24 18:20:00'),
 Timestamp('2025-07-24 18:21:00'),
 Timestamp('2025-07-24 18:22:00'),
 Timestamp('2025-07-24 18:23:00'),
 Timestamp('2025-07-24 18:24:00'),
 Timestamp('2025-07-24 18:25:00'),
 Timestamp('2025-07-24 18:26:00'),
 Timestamp('2025-07-24 18:27:00'),
 Timestamp('2025-07-24 18:28:00'),
 Timestamp('2025-07-24 18:29:00'),
 Timestamp('2025-07-24 18:30:00'),
 Timestamp('2025-07-24 18:31:00'),
 Timestamp('2025-07-24 18:32:00'),
 Timestamp('2025-07-24 18:33:00'),
 Timestamp('2025-07-24 18:34:00'),
 Timestamp('2025-07-24 18:35:00'),
 Timestamp('2025-07-24 18:36:00'),
 Timestamp('2025-07-24 18:37:00'),
 Timestamp('2025-07-24 18:38:00'),
 Timestamp('2025-07-24 18:39:00'),
 Timestamp('2025-07-24 18:40:00'),
 Timestamp('2025-07-24 18:41:00'),
 Timestamp('2025-07-24 18:42:00'),
 Timestamp('2025-07-24 18:43:00'),
 Timestamp('2025-07-24 18:44:00'),
 Timestamp('2025-07-24 18:45:00'),
 Timestamp('2025-07-24 18:46:00'),
 Timestamp('2025-07-24 18:47:00'),
 Timestamp('2025-07-24 18:48:00'),
 Timestamp('2025-07-24 18:49:00'),
 Timestamp('2025-07-24 18:50:00'),
 Timestamp('2025-07-24 18:51:00'),
 Timestamp('2025-07-24 18:52:00'),
 Timestamp('2025-07-24 18:53:00'),
 Timestamp('2025-07-24 18:54:00'),
 Timestamp('2025-07-24 18:55:00'),
 Timestamp('2025-07-24 18:56:00'),
 Timestamp('2025-07-24 18:57:00'),
 Timestamp('2025-07-24 18:58:00'),
 Timestamp('2025-07-24 18:59:00'),
 Timestamp('2025-07-24 19:00:00')]

In [122]:
canon_idx

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]