In [ ]:
import pandas as pd

df = pd.read_parquet('data/TSLA_1min.parquet')

df[df.timestamp.dt.date == '2025-07-21']

Empty DataFrame
Columns: [timestamp, symbol, open, close, high, low, mean, std, trade_count, volume, dollar_volume, cond_is_regular, odd_lot_count, buy_volume, sell_volume, order_flow_imbalance, dollar_order_flow_imbalance, kyle_lambda, avg_price_acceleration, price_acceleration_std, consecutive_trades_ratio, volume_weighted_momentum, avg_trade_size, trade_size_std, max_trade_size, buy_trade_count, sell_trade_count, intertrade_ms_mean, intertrade_ms_std, intertrade_ms_min, intertrade_ms_max, cnt_large, cnt_mid, cnt_small, cnt_tiny, vwap, order_flow_ratio, dollar_order_flow_ratio, buy_sell_ratio, trade_direction_ratio, price_impact_per_dollar, trade_return, volatility_proxy, price_range, mid_bar_pos, turnover_rate, trade_intensity, roll_spread_proxy, price_reversal]
Index: []

[0 rows x 49 columns]

In [104]:
df = pd.read_parquet('data/TSLA_1min.parquet')

df

,timestamp,symbol,open,close,high,low,mean,std,trade_count,volume,...,trade_direction_ratio,price_impact_per_dollar,trade_return,volatility_proxy,price_range,mid_bar_pos,turnover_rate,trade_intensity,roll_spread_proxy,price_reversal
0,2025-01-02 14:30:00,TSLA,390.360,389.370,392.520,388.55,390.532619,0.718331,420.0,19112.0,...,-0.009524,0.000372,0.009882,0.001839,0.010170,0.206549,420.0,488.968119,7.438165e-06,-0.0000
1,2025-01-02 14:31:00,TSLA,389.150,386.670,389.620,385.73,387.424490,0.867394,245.0,22401.0,...,-0.053061,0.000262,-0.006934,0.002239,0.009996,0.241645,245.0,1055.001765,6.852267e-05,2.4552
2,2025-01-02 14:32:00,TSLA,385.735,385.720,387.700,385.71,386.768963,0.495379,135.0,7218.0,...,-0.088889,0.000267,-0.002457,0.001281,0.005159,0.005025,135.0,288.659749,1.703666e-05,0.0372
3,2025-01-02 14:33:00,TSLA,385.740,382.420,386.170,382.41,384.481279,1.113702,172.0,10315.0,...,0.029070,0.000184,-0.008555,0.002897,0.009747,0.002660,172.0,490.531374,2.101962e-05,0.0498
4,2025-01-02 14:34:00,TSLA,382.450,381.795,383.980,381.70,382.757703,0.599312,111.0,4504.0,...,0.090090,0.000333,-0.001634,0.001566,0.005962,0.041667,111.0,205.250783,1.398238e-05,2.1746
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53773,2025-07-23 19:56:00,TSLA,332.430,332.760,332.830,332.40,332.593273,0.116735,55.0,3741.0,...,0.236364,0.000109,0.001204,0.000351,0.001294,0.837209,55.0,50.208685,9.045987e-07,0.0033
53774,2025-07-23 19:57:00,TSLA,332.740,332.680,332.945,332.67,332.797862,0.059296,138.0,9395.0,...,-0.086957,0.000038,-0.000240,0.000178,0.000826,0.036364,138.0,313.264001,2.893411e-07,-0.0198
53775,2025-07-23 19:58:00,TSLA,332.670,332.760,332.870,332.63,332.794836,0.047090,61.0,2878.0,...,0.049180,0.000063,0.000240,0.000141,0.000721,0.541667,61.0,61.993211,5.781256e-08,-0.0054
53776,2025-07-23 19:59:00,TSLA,332.700,333.040,333.040,332.59,332.740186,0.088296,161.0,12505.0,...,-0.031056,0.000056,0.000841,0.000265,0.001353,1.000000,161.0,426.710096,2.023439e-07,0.0306
53777,2025-07-23 20:00:00,TSLA,333.040,333.040,333.040,333.04,333.040000,0.000000,0.0,0.0,...,0.000000,0.000000,333.040000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000e+00,0.0000

In [68]:
import datetime

datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")

'2025-07-24T14:43:54Z'

In [71]:
from datetime import datetime
import pytz

def nyc_now() -> datetime:
    return datetime.now(pytz.timezone("UTC")).replace(tzinfo=None)
nyc_now()

datetime.datetime(2025, 7, 24, 18, 45, 46, 914698)

In [106]:
from pandas_market_calendars import get_calendar, date_range
import pandas as pd

nyse = get_calendar("NYSE")
start_time = "2025-07-23 20:01:00"
end_time = "2025-07-24 19:00:00"
start_date = pd.to_datetime(start_time)
end_date = pd.to_datetime(end_time)

sched = nyse.schedule(start_date=start_date, end_date=end_date, tz="UTC")
canon_idx = date_range(sched, frequency="1min", closed="both")
canon_idx = canon_idx.tz_localize(None)
canon_idx = canon_idx[canon_idx.time >= pd.to_datetime(start_time).time()]
canon_idx = canon_idx[canon_idx.time <= pd.to_datetime(end_time).time()]
canon_idx

DatetimeIndex([], dtype='datetime64[ns]', freq=None)

In [102]:
sched

                         market_open              market_close
2025-01-02 2025-01-02 14:30:00+00:00 2025-01-02 21:00:00+00:00